package com.example.lab7moviles.domain.model

data class Ingredients(
    val id: Int,
    val name: String,
    val bebida: String,
    val categoria: String,
    val area: String,
    val ins: String,
    val imagen: String,
    val tags: String,
    val video: String,
    val ing1: String,
    val ing2: String,
    val ing3: String,
    val ing4: String,
    val ing5: String,
    val ing6: String,
    val ing7: String,
    val ing8: String,
    val ing9: String,
    val ing10: String,
    val ing11: String,
    val ing12: String,
    val ing13: String,
    val ing14: String,
    val ing15: String,
    val ing16: String,
    val ing17: String,
    val ing18: String,
    val ing19: String,
    val ing20: String,
    val medida1: String,
    val medida2: String,
    val medida3: String,
    val medida4: String,
    val medida5: String,
    val medida6: String,
    val medida7: String,
    val medida8: String,
    val medida9: String,
    val medida10: String,
    val medida11: String,
    val medida12: String,
    val medida13: String,
    val medida14: String,
    val medida15: String,
    val medida16: String,
    val medida17: String,
    val medida18: String,
    val medida19: String,
    val medida20: String,
    val fuente: String,
    val imgfuente: String,
    val creative: String,
    val date: Int,




    )
